services:
  smee:
    image: binaryrat/smee
    container_name: smee

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheapvpn
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrator:
    image: binaryrat/migrator:1
    restart: on-failure

  bot:
    build: .
    container_name: bot
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
    - "3000:3000"
    - "51825:51820/tcp"
    - "51825:51820/udp"
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/cheapvpn
    depends_on:
      - postgres
    restart: on-failure 

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
