services:
  smee:
    image: binaryrat/smee
    container_name: smee
    command:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheapvpn
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  bot:
    image: binaryrat/vpnbot:mvp
    container_name: bot
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
    - "3000:3000"
    - "51820:51820/tcp"
    - "51820:51820/udp"
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/cheapvpn
    depends_on:
      - postgres
    restart: on-failure 

  migrator:
    image: binaryrat/migrator:1
    restart: on-failure
volumes:
  pgdata: