global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:2112']
    metrics_path: '/metrics'
  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets: [ 'kafka-lag-exporter:8000' ]
